// Package searchindex implements the Azure ARM Searchindex service API version 2019-05-06.
//
// Client that can be used to query an index and upload, merge, or delete documents.
package searchindex

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/Azure/go-autorest/autorest"
)

const (
	// DefaultSearchDNSSuffix is the default value for search dns suffix
	DefaultSearchDNSSuffix = "search.windows.net"
)

// BaseClient is the base client for Searchindex.
type BaseClient struct {
	autorest.Client
	SearchServiceName string
	SearchDNSSuffix   string
	IndexName         string
}

// New creates an instance of the BaseClient client.
func New(searchServiceName string, indexName string) BaseClient {
	return NewWithoutDefaults(searchServiceName, indexName, DefaultSearchDNSSuffix)
}

// NewWithoutDefaults creates an instance of the BaseClient client.
func NewWithoutDefaults(searchServiceName string, indexName string, searchDNSSuffix string) BaseClient {
	return BaseClient{
		Client:            autorest.NewClientWithUserAgent(UserAgent()),
		SearchServiceName: searchServiceName,
		SearchDNSSuffix:   searchDNSSuffix,
		IndexName:         indexName,
	}
}
